services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/mydatabase
      - JWT_SECRET=your_secret_key
      - JWT_EXPIRES_IN=1d
      - NODE_ENV=development
      - DEFAULT_STOCK_AMOUNT=200
      - MAX_PURCHASE_PER_USER=5
    volumes:
      - .:/app
      - /app/node_modules

  mongodb:
    image: mongo:7
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
